from typing import Generic, TypeVar, List, Optional
from sqlmodel import SQLModel, Field

T = TypeVar("T")

# endpoints that return a list of item
class PaginatedResponse(SQLModel, Generic[T]):
    message: str # status message or code
    data: List[T]  = Field(default_factory=list) #list of actual results (users, satellites, etc.).
    total: int # total number of records in DB
    page: int # current page number
    page_size: int # how many items per page
    total_pages: int # total number of page

# endpoints that return a single item or a succcess message
class SuccessResponse(SQLModel, Generic[T]):
    message: str # status message or code
    data: Optional[T] = None # the acutal resources

# error message
class ErrorResponse(SQLModel):
    detail: str # description of what went wrong

# Centralized list of message codes (success & error)
from enum import Enum
class MessageCode(str, Enum):
    # MESSAGE CODE BASE #
    PAYLOAD_NOT_FOUND = "PAYLOAD_NOT_FOUND"
    ERROR_BAD_REQUEST = "ERROR_BAD_REQUEST"

    # USER MESSAGE #
    CREATE_USER_SUCCESSFULLY = "CREATE_USER_SUCCESSFULLY"
    CREATE_USER_FAILED = "CREATE_USER_FAILED"
    USER_LOGIN_SUCCESSFULLY = "USER_LOGIN_SUCCESSFULLY"
    USER_LOGIN_FAILED = "USER_LOGIN_FAILED"
    UPDATE_USER_SUCCESSFULLY = "UPDATE_USER_SUCCESSFULLY"
    UPDATE_USER_FAILED = "UPDATE_USER_FAILED"
    DELETE_USER_SUCCESSFULLY = "DELETE_USER_SUCCESSFULLY"
    DELETE_USER_FAILED = "DELETE_USER_FAILED"
    USER_ID_REQUIRED = "USER_ID_REQUIRED"
    USER_NOT_FOUND = "USER_NOT_FOUND"
    USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS"
    INVALID_USER_ID = "INVALID_USER_ID"
    USER_ID_IS_MISMATCH = "USER_ID_IS_MISMATCH"
    GET_USER_FAILED = "GET_USER_FAILED"
    GET_USER_SUCCESSFULLY = "GET_USER_SUCCESSFULLY"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"


    # CONVERSATION MESSAGE #
    CREATE_CONVERSATION_SUCCESSFULLY = "CREATE_CONVERSATION_SUCCESSFULLY"
    CREATE_CONVERSATION_FAILED = "CREATE_CONVERSATION_FAILED"
    UPDATE_CONVERSATION_SUCCESSFULLY = "UPDATE_CONVERSATION_SUCCESSFULLY"
    UPDATE_CONVERSATION_FAILED = "UPDATE_CONVERSATION_FAILED"
    DELETE_CONVERSATION_SUCCESSFULLY = "DELETE_CONVERSATION_SUCCESSFULLY"
    DELETE_CONVERSATION_FAILED = "DELETE_CONVERSATION_FAILED"
    CONVERSATION_ID_REQUIRED = "CONVERSATION_ID_REQUIRED"
    CONVERSATION_NOT_FOUND = "CONVERSATION_NOT_FOUND"
    CONVERSATION_ALREADY_EXISTS = "CONVERSATION_ALREADY_EXISTS"
    INVALID_CONVERSATION_ID = "INVALID_CONVERSATION_ID"
    CONVERSATION_ID_IS_MISMATCH = "CONVERSATION_ID_IS_MISMATCH"
    GET_CONVERSATION_FAILED = "GET_CONVERSATION_FAILED"
    GET_CONVERSATION_SUCCESSFULLY = "GET_CONVERSATION_SUCCESSFULLY"

    # MESSAGE #
    CREATE_MESSAGE_SUCCESSFULLY = "CREATE_MESSAGE_SUCCESSFULLY"
    CREATE_MESSAGE_FAILED = "CREATE_MESSAGE_FAILED"
    MESSAGE_ID_REQUIRED = "MESSAGE_ID_REQUIRED"
    MESSAGE_NOT_FOUND = "MESSAGE_NOT_FOUND"
    MESSAGE_ALREADY_EXISTS = "MESSAGE_ALREADY_EXISTS"
    INVALID_MESSAGE_ID = "INVALID_MESSAGE_ID"
    MESSAGE_ID_IS_MISMATCH = "MESSAGE_ID_IS_MISMATCH"
    GET_MESSAGE_FAILED = "GET_MESSAGE_FAILED"
    GET_MESSAGE_SUCCESSFULLY = "GET_MESSAGE_SUCCESSFULLY"

    # MOOD LOG MESSAGE #
    CREATE_MOOD_LOG_SUCCESSFULLY = "CREATE_MOOD_LOG_SUCCESSFULLY"
    CREATE_MOOD_LOG_FAILED = "CREATE_MOOD_LOG_FAILED"
    UPDATE_MOOD_LOG_SUCCESSFULLY = "UPDATE_MOOD_LOG_SUCCESSFULLY"
    UPDATE_MOOD_LOG_FAILED = "UPDATE_MOOD_LOG_FAILED"
    DELETE_MOOD_LOG_SUCCESSFULLY = "DELETE_MOOD_LOG_SUCCESSFULLY"
    DELETE_MOOD_LOG_FAILED = "DELETE_MOOD_LOG_FAILED"
    MOOD_LOG_ID_REQUIRED = "MOOD_LOG_ID_REQUIRED"
    MOOD_LOG_NOT_FOUND = "MOOD_LOG_NOT_FOUND"
    MOOD_LOG_ALREADY_EXISTS = "MOOD_LOG_ALREADY_EXISTS"
    INVALID_MOOD_LOG_ID = "INVALID_MOOD_LOG_ID"
    MOOD_LOG_ID_IS_MISMATCH = "MOOD_LOG_ID_IS_MISMATCH"
    GET_MOOD_LOG_FAILED = "GET_MOOD_LOG_FAILED"
    GET_MOOD_LOG_SUCCESSFULLY = "GET_MOOD_LOG_SUCCESSFULLY"

    # JOURNAL MESSAGE #
    CREATE_JOURNAL_SUCCESSFULLY = "CREATE_JOURNAL_SUCCESSFULLY"
    CREATE_JOURNAL_FAILED = "CREATE_JOURNAL_FAILED"
    UPDATE_JOURNAL_SUCCESSFULLY = "UPDATE_JOURNAL_SUCCESSFULLY"
    UPDATE_JOURNAL_FAILED = "UPDATE_JOURNAL_FAILED"
    DELETE_JOURNAL_SUCCESSFULLY = "DELETE_JOURNAL_SUCCESSFULLY"
    DELETE_JOURNAL_FAILED = "DELETE_JOURNAL_FAILED"
    JOURNAL_ID_REQUIRED = "JOURNAL_ID_REQUIRED"
    JOURNAL_NOT_FOUND = "JOURNAL_NOT_FOUND"
    JOURNAL_ALREADY_EXISTS = "JOURNAL_ALREADY_EXISTS"
    INVALID_JOURNAL_ID = "INVALID_JOURNAL_ID"
    JOURNAL_ID_IS_MISMATCH = "JOURNAL_ID_IS_MISMATCH"
    GET_JOURNAL_FAILED = "GET_JOURNAL_FAILED"
    GET_JOURNAL_SUCCESSFULLY = "GET_JOURNAL_SUCCESSFULLY"

    # CONTACT ALERT MESSAGE #
    CREATE_CONTACT_ALERT_SUCCESSFULLY = "CREATE_CONTACT_ALERT_SUCCESSFULLY"
    CREATE_CONTACT_ALERT_FAILED = "CREATE_CONTACT_ALERT_FAILED"
    UPDATE_CONTACT_ALERT_SUCCESSFULLY = "UPDATE_CONTACT_ALERT_SUCCESSFULLY"
    UPDATE_CONTACT_ALERT_FAILED = "UPDATE_CONTACT_ALERT_FAILED"
    DELETE_CONTACT_ALERT_SUCCESSFULLY = "DELETE_CONTACT_ALERT_SUCCESSFULLY"
    DELETE_CONTACT_ALERT_FAILED = "DELETE_CONTACT_ALERT_FAILED"
    CONTACT_ALERT_ID_REQUIRED = "CONTACT_ALERT_ID_REQUIRED"
    CONTACT_ALERT_NOT_FOUND = "CONTACT_ALERT_NOT_FOUND"
    CONTACT_ALERT_ALREADY_EXISTS = "CONTACT_ALERT_ALREADY_EXISTS"
    INVALID_CONTACT_ALERT_ID = "INVALID_CONTACT_ALERT_ID"
    CONTACT_ALERT_ID_IS_MISMATCH = "CONTACT_ALERT_ID_IS_MISMATCH"
    GET_CONTACT_ALERT_FAILED = "GET_CONTACT_ALERT_FAILED"
    GET_CONTACT_ALERT_SUCCESSFULLY = "GET_CONTACT_ALERT_SUCCESSFULLY"

    # CONTACT ALERT LOG MESSAGE #
    CREATE_CONTACT_ALERT_LOG_SUCCESSFULLY = "CREATE_CONTACT_ALERT_LOG_SUCCESSFULLY"
    CREATE_CONTACT_ALERT_LOG_FAILED = "CREATE_CONTACT_ALERT_LOG_FAILED"
    UPDATE_CONTACT_ALERT_LOG_SUCCESSFULLY = "UPDATE_CONTACT_ALERT_LOG_SUCCESSFULLY"
    UPDATE_CONTACT_ALERT_LOG_FAILED = "UPDATE_CONTACT_ALERT_LOG_FAILED"
    DELETE_CONTACT_ALERT_LOG_SUCCESSFULLY = "DELETE_CONTACT_ALERT_LOG_SUCCESSFULLY"
    DELETE_CONTACT_ALERT_LOG_FAILED = "DELETE_CONTACT_ALERT_LOG_FAILED"
    CONTACT_ALERT_LOG_ID_REQUIRED = "CONTACT_ALERT_LOG_ID_REQUIRED"
    CONTACT_ALERT_LOG_NOT_FOUND = "CONTACT_ALERT_LOG_NOT_FOUND"
    CONTACT_ALERT_LOG_ALREADY_EXISTS = "CONTACT_ALERT_LOG_ALREADY_EXISTS"
    INVALID_CONTACT_ALERT_LOG_ID = "INVALID_CONTACT_ALERT_LOG_ID"
    CONTACT_ALERT_LOG_ID_IS_MISMATCH = "CONTACT_ALERT_LOG_ID_IS_MISMATCH"
    GET_CONTACT_ALERT_LOG_FAILED = "GET_CONTACT_ALERT_LOG_FAILED"
    GET_CONTACT_ALERT_LOG_SUCCESSFULLY = "GET_CONTACT_ALERT_LOG_SUCCESSFULLY"

    # AUDIT MESSAGE #
    LOGIN_SUCCESSFULLY = "LOGIN_SUCCESSFULLY"
    LOGIN_FAILED = "LOGIN_FAILED"
    LOGOUT_SUCCESSFULLY = "LOGOUT_SUCCESSFULLY"
    UNAUTHORIZED = "UNAUTHORIZED"
    FORBIDDEN = "FORBIDDEN"

    # SYSTEM MESSAGE #
    SERVER_ERROR = "SERVER_ERROR"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    
    
    CREATE_PAYLOAD_SUCCESSFULLY = "CREATE_PAYLOAD_SUCCESSFULLY"
    SAT_NOT_FOUND = "SAT_NOT_FOUND"
    SAT_DELETE_FAILED = "SAT_DELETE_FAILED"
    SAT_DELETE_SUCCESS = "SAT_DELETE_SUCCESS"
    FILTER_PAYLOAD_SUCCESSFULLY = "FILTER_PAYLOAD_SUCCESSFULLY"
    PAYLOAD_ID_REQUIRED = "PAYLOAD_ID_REQUIRED"
    PAYLOAD_DELETE_FAILED = "PAYLOAD_DELETE_FAILED"
    PAYLOAD_DELETE_SUCCESS = "PAYLOAD_DELETE_SUCCESS"
    UPDATE_PAYLOAD_SUCCESSFULLY = "UPDATE_PAYLOAD_SUCCESSFULLY"
    PAYLOAD_IN_USE = "PAYLOAD_IN_USE"
    SAT_PAYLOAD_INSERT_SUCCESSFULLY = "SAT_PAYLOAD_INSERT_SUCCESSFULLY"
    SATELLITE_ID_IS_MISMATCH = "SATELLITE_ID_IS_MISMATCH"
    UPDATE_SAT_PAYLOAD_SUCCESSFULLY = "UPDATE_SAT_PAYLOAD_SUCCESSFULLY"
    DELETE_SAT_PAYLOAD_SUCCESSFULLY = "DELETE_SAT_PAYLOAD_SUCCESSFULLY"